- src/adapters/peggedAssets/bacon-protocol-home/index.ts
- src/adapters/peggedAssets/index.ts
Adding HomeCoin (HOME) to the stablecoin list.
See https://github.com/DefiLlama/DefiLlama-Adapters/pull/3366 for TVL adaptor.
Some basic info:
Twitter Link:
https://twitter.com/homecoinfinance
List of audit links if any:
https://files.homecoin.finance/bacon-protocol-full-audit.pdf
Website Link:
https://www.homecoin.finance/
Logo 
https://files.homecoin.finance/homecoin-icon-500.png
Current TVL:
6,747,567
Chain:
Ethereum
Coingecko ID (so your TVL can appear on Coingecko): (https://api.coingecko.com/api/v3/coins/list)
bacon-protocol-home
Coinmarketcap ID (so your TVL can appear on Coinmarketcap): (https://api.coinmarketcap.com/data-api/v3/map/all?listing_status=active,inactive,untracked&start=1&limit=10000)
20520
Short Description (to be shown on DefiLlama):
A StableCoin backed by U.S. …
> Add HomeCoin stable adaptor

- src/adapters/peggedAssets/index.ts
- src/adapters/peggedAssets/prices/index.ts
- src/adapters/peggedAssets/xai/index.ts
This adds the XAI stablecoin by the Silo Finance team into the peggedAsset adapters, along with a Uniswap price feed.
> feat(peggedAssets/xai): adds an adapter for the XAI stablecoin by Silo Finance

- src/adapters/peggedAssets/digital-standard-unit/index.ts
Updates DSU's issuance with Optimism and Arbitrum tracking, and adds `unreleased` support for DSU that is in the batchers which contain unbacked DSU that is released when a user submits USDC to be wrapped into DSU.
> Update DSU issuance with multi-chain, unreleased

- src/adapters/peggedAssets/euroe-stablecoin/index.ts
EUROe has been deployed on Arbitrum One natively.
Cross reference addresses at https://dev.euroe.com/docs/Stablecoin/contract-addresses#arbitrum-addresses
> Add Arbitrum adapter

- src/adapters/peggedAssets/binance-usd/index.ts
- src/adapters/peggedAssets/tether/index.ts
- src/adapters/peggedAssets/usd-coin/index.ts
Here to rectify my mistake of misuing the minted tokens. ThunderCore stablecoins originates from other networks.
> fix thundercore stablecoins

- src/adapters/peggedAssets/pando-usd/index.ts
According to the official post, only the Rings protocol was affected. Attackers didn't mint Pando USD.
https://pando.im/news/2022/2022-11-06-alert-to-pando-community-hack-of-pando-rings/
> recover the data of Pando USD

- src/adapters/peggedAssets/magic-internet-money/index.ts
Correctly consider Abracadabra's GM cauldrons on Arbitrum.
> feat(abracadabra): Add support for GM cauldrons on Arbitrum

- src/adapters/peggedAssets/magic-internet-money/index.ts
Consider gmLINK cauldron (borrow market) for circulating supply.
> feat(abracadabra): Add support for gmLINK cauldron

- src/adapters/peggedAssets/liquity-usd/index.ts
These were previously commented out. LUSD has low supply on each chain, but it should still be tracked imo.
> add LUSD for zkSync Era and Polygon zkEVM

- src/adapters/peggedAssets/llama-helper/near.js
- src/adapters/peggedAssets/tether/index.ts
This PR has two parts:
1. Added native USDC and USDT contract addresses to the token mapping in the near.js helper file 
2. Added a function to calculate native USDT supply on NEAR to the tether index.ts file
> fix near stablecoin balances

- src/peggedData/peggedData.ts
Current price targets MBRN which is the governance token of CDT rather than the pegged asset itself.
https://www.coingecko.com/en/coins/collateralized-debt-token
Also updated gitbook to the correct link
> Add CDT Coingecko

- src/adapters/peggedAssets/gyen/index.ts
- src/adapters/peggedAssets/zusd/index.ts
Hi Team, We added GYEN/ZUSD on Solana Network.
GYEN: Crn4x1Y2HUKko7ox2EZMT6N2t2ZyH7eKtwkBGVnhEq1g
ZUSD: FrBfWJ4qE5sCzKm3k3JaAtqZcXUh4LvJygDeketsrsH4
Tests are passed. Thank you!
```
% npm run-script test zusd peggedUSD
> defillama-server@1.0.0 pretest
> npm run prebuild
> defillama-server@1.0.0 prebuild
> npx ts-node src/cli/buildRequires.ts
> defillama-server@1.0.0 test
> cd src/adapters/peggedAssets && npx ts-node test "zusd" "peggedUSD"
(node:82076) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
GMO API success
GMO API success
--- ethereum ---
minted                    18.75 M
circulating               18.75 M
--- optimism ---
minted …
```
> update GYEN and ZUSD

- src/adapters/peggedAssets/gai-stablecoin/index.ts
- src/adapters/peggedAssets/helper/chains.json
- src/adapters/peggedAssets/index.ts
- src/adapters/peggedAssets/llama-helper/portedTokens.js
- src/peggedData/peggedData.ts
Add Gai Stablecoin to DefiLlama
Our website is `https://goku.money/`
GAI `https://www.coingecko.com/en/coins/goku-money-gai`
And here is the test logs.
`npx ts-node test gai-stablecoin/index.ts peggedUSD`
```
------ ERROR ------
Bridge data not found on chain manta. Use sumSingleBalance from helper/generalUtil to add bridge data.
--- manta ---
minted                    69.50 k
circulating               69.50 k
Total circulating         69.50 k
```
> add gai-stablecoin(pegged with USD）

- src/adapters/peggedAssets/inter-stable-token/index.ts
Hey DefiLlama team, we recently performed a chain upgrade that upgraded cosmos-sdk from 0.45 to 0.46 and as a result, the URL scheme for getting supply for a certain denom needs to be updated.
```
curl https://rest.cosmos.directory/agoric/cosmos/bank/v1beta1/supply/by_denom?denom=uist
{
"amount": {
"denom": "uist",
"amount": "1384674829604"
}
}                                                                                                                                                                                                                                                                                                                        
```
vs
```
curl https://rest.cosmos.directory/agoric/cosmos/bank/v1beta1/supply/uist
{
"code": 12,
"message": "Not Implemented",
"details": …
```
> fix: update URL to get IST supply

- src/adapters/peggedAssets/index.ts
- src/adapters/peggedAssets/usual-usd/index.ts
- src/peggedData/peggedData.ts
chain: **Ethereum**
address: **0x73A15FeD60Bf67631dC6cd7Bc5B6e8da8190aCF5**
symbol: **USD0**
website: **https://usual.money**
twitter: **https://x.com/usualmoney**
wiki: **https://gitbook.usual.money**
Usual enables an RWA-stablecoin that provides a high standard of security and transparency, while redistributing the generated value in the form of speculative yield in $USUAL, the Usual governance token
On Usual users can deposit either USYC or USDC as collateral to mint USD0. USD0 is backed 1:1 by collateral exclusively in the form of very short-term RWAs (Real-World Assets)
> Adapter and listing Usual USD

- src/adapters/peggedAssets/anzen-usdz/index.ts
- src/adapters/peggedAssets/index.ts
- src/peggedData/peggedData.ts
Although Anzen only issue USDz on the mainnet, we uniformly use "issued" in this pr due to the cross-chain standard adopting the mint/burn model.
```
npx ts-node --transpile-only test.ts anzen-usdz peggedUSD
--- ethereum ---
minted                    4.99 M
circulating               4.99 M
--- base ---
minted                    19.28 M
circulating               19.28 M
--- blast ---
minted                    103.95 k
circulating               103.95 k
--- manta ---
minted                    0.409
circulating               0.409
Total circulating         24.37 M
```
> listing Anzen USDz

- src/adapters/peggedAssets/index.ts
- src/adapters/peggedAssets/m0-m/index.ts
This PR adds the token M by [M^0](https://m0.org/)
M: https://etherscan.io/token/0x866A2BF4E572CbcF37D5071A7a58503Bfb36be1b
Supporting links
Official website: https://www.m0.org/
Whitepaper: https://docs.m0.org/portal
Twitter / X: https://x.com/m0foundation
Linkedin: https://linkedin.com/company/m0-labs
> feat: add M token by M^0 - https://m0.org

- src/adapters/peggedAssets/ondo-us-dollar-yield/index.ts
Ondo's USDY token has been bridged from Noble to 4 cosmos chains thru IBC:
- Mantra
- Injective
- Osmosis
- Penumbra
> Add Ondo USDY on Mantra and Penumbra

- src/adapters/peggedAssets/usual-usd/index.ts
This PR adds the Usd0 arbitrum data to the existing usual adapter
chain: Arbitrum
address: 0x35f1C5cB7Fb977E669fD244C567Da99d8a3a6850
symbol: USD0
> Add Usd0 on Arbitrum data

- src/adapters/peggedAssets/tether/config.ts
- src/peggedData/bridgeData.ts
- src/utils/normalizeChain.ts
Hi, I would like to request update the information for Viction chain on Stable Page:
1. Update chain display name from `TomoChain` to `Viction`
2. Update the official USDT to the new one which is `0x69b946132b4a6c74cd29ba3ff614ceea1ef9ff2b`. please verify here > https://x.com/BuildOnViction/status/1871178874685648919
3. Update the symbol from `TOMO` to `VIC`. Please check > https://www.coingecko.com/en/coins/viction
4. Update bridge protocol to the new one
Thank you!
> Update Viction info 

- src/peggedData/peggedData.ts
location for audits in the documentation changed.
> fix: crvusd audits link

- src/adapters/peggedAssets/index.ts
- src/adapters/peggedAssets/level-usd/index.ts
Hey team! Here's the metadata we'd like to add to our listing for Level USD onto the stablecoin page.
_Name_: Level USD
_Symbol_: `lvlUSD`
_Icon_: https://storage.googleapis.com/level-public/icons/lvlusd.svg
_Website_: https://level.money
_Twitter_: https://twitter.com/levelusd
_Description_
Level USD is a stablecoin backed by USDC and USDT that are deployed on blue-chip restaking and lending protocols. Users can stake Level USD to earn stacked restaking and lending yield with the stable reserves of battle-tested stablecoins.
Category: crypto-backed
_Minting and Redemption_
Users can mint Level USD with USDC and USDT permissionlessly. The protocol deploys this collateral into blue-chip restaking and lending protocols to generate yield for users.
> Add Level USD

- src/adapters/peggedAssets/monerium-eur-money/index.ts
**Changes**:
* Monerium EURe tokens on Ethereum, Polygon, and Gnosis have been upgraded from V1 to V2, [see the announcement here](https://monerium.dev/docs/contracts-v2)
* Added EURe on Arbitrum, Scroll, and Linea. [See tokens here on the official Monerium dev site](https://monerium.dev/docs/tokens).
> peggedAsset update - monerium-eur-money

- src/adapters/peggedAssets/usdd/index.ts
Since USDD has migrated from `TPYmHEhy5n8TCEfYGqW2rPxsghSfzghPDn` to `TXDk8mbtRbXeYuMNS83CfKPaYYT8XWv9Hz` on the TRON network, all related bridged tokens have also been migrated. The total supply of USDD needs to be calculated from these tokens.
> fix: use new usdd tokens

- src/adapters/peggedAssets/eur-coinvertible/config.ts
- src/adapters/peggedAssets/eur-coinvertible/index.ts
- src/adapters/peggedAssets/index.ts
Integrates Euro Coinvertible (EURCV) into the pegged assets adapters. This includes support for issuance and unreleased tracking on Ethereum and Solana chains, along with the necessary configurations and helper functions.
> Add EURCV (Euro Coinvertible) adapter

- src/adapters/peggedAssets/usd-coin/config.ts
On April 25, the Ronin bridge migrated to Chainlinks CCIP bridge. 
https://roninchain.com/blog/posts/the-ronin-bridge-chainlink-ccip-migration-is-complete
All tokens have been moved from the old bridge contract to CCIP pools.
Ronin USDC CCIP pool on Ethereum: https://etherscan.io/address/0xc2e3a3c18ccb634622b57ff119a1c8c7f12e8c0c
This PR changes the old bridge contract address to the new pool address.
Circulating USDC supply on Ronin is 22.915M at the time of writing.
> fix USDC on Ronin

- src/adapters/peggedAssets/smardex-usdn/index.ts
{
name: "SMARDEX USDN",
address: "0xde17a000ba631c5d7c2bd9fb692efea52d90dee2",
symbol: "USDN",
url: "https://etherscan.io/token/0xde17a000ba631c5d7c2bd9fb692efea52d90dee2",
description: "The USDN token is the first synthetic U.S. dollar backed by a structured product utilizing a delta-Neutral strategy. Unlike traditional stablecoins, whose value is guaranteed by centralized entities, the value of a synthetic dollar is determined by a purely mathematical financial process.",
mintRedeemDescription: "Deposit Lido token (WSTETH) in USDN Vault allows to Mint USDN tokens and profit from its yield. Redeem Lido burns USDN",
onCoinGecko: "true",
gecko_id: "smardex-usdn",
cmcId: "smardex-usdn",
pegType: "peggedUSD",
pegMechanism: "crypto-backed",
priceSource: "defillama",
auditLinks: …
> feat: publish USDN token supply in stablecoin

- src/adapters/peggedAssets/weusd/index.ts
- src/peggedData/peggedData.ts
This PR uncomments and updates the `chainContracts` object in the WEUSD adapter to support new contract addresses for the `base`, `arbitrum`, and `bsc` chains. It also enables `addChainExports` in the adapter to include these chains, and updates the project description for WEUSD to reflect multi-chain deployment.
---
- **Added chains:** `base`, `arbitrum`, `bsc`
- **Contract address for all chains:**  
`0xdd73EA766B80417C0607A3f08E34A0C415D89D56`
- **Purpose:** Enables WEUSD supply tracking across multiple chains for more comprehensive analytics.
- The adapter now uses `addChainExports(chainContracts)` to ensure all supported chains are included in the exported object, making the data available to the API and frontend.
---
- Enables multi-chain supply tracking for WEUSD
- Ensures adapter …
> Add Multi-Chain Support and Update WEUSD Adapter & Description

- src/adapters/peggedAssets/index.ts
- src/adapters/peggedAssets/noble-dollar-usdn/index.ts
Add adapter for Noble Dollar (USDN).
- Token: Noble Dollar (USDN)
- Chain: Noble 
- Denomination: uusdn
- Decimals: 6
- CoinGecko ID: noble-dollar-usdn
> Add Noble Dollar (USDN) adapter

- src/adapters/peggedAssets/weusd/index.ts
Added support for the 'plume' and 'hashkey' chains in the WEUSD pegged asset adapter, using the same issued contract address as other chains.
> Add plume and hashkey chains to WEUSD adapter

- src/adapters/peggedAssets/main-street-usd/index.ts
**NOTE**
---
Mainstreet USD (msUSD)
https://mainstreet.finance/
https://drive.google.com/file/d/1t4IEzGHvgH2Ok9eqY702JNElf5_rnzwo/view?usp=sharing
https://www.coingecko.com/en/coins/main-street-usd
Yield-bearing synthetic dollar - democratizing access to the options volatility arbitrage
msUSD can be minted at https://mainstreet.finance/mint by depositing USDC. The depositor will be minted 1:1 msUSD. Redemptions can occur on the same UI.
https://sonicscan.org/address/0xE5Fb2Ed6832deF99ddE57C0b9d9A56537C89121D
$msUSD
> Adding msUSD as a pegged asset

- src/peggedData/peggedData.ts
Correct price LP:
https://app.uniswap.org/explore/pools/ethereum/0x14d7aab5b4bca6a02e52ac22520b033bf35f4091
Coingecko is broken.
CMC price feed is correct:
https://coinmarketcap.com/currencies/a7a5/
> Hide Coingecko feed

- src/adapters/peggedAssets/index.ts
- src/adapters/peggedAssets/unity-2/index.ts
- src/peggedData/peggedData.ts
> XSY: Adds UTY for listing
