src/adapters/peggedAssets/dola-usd/index.ts, src/adapters/peggedAssets/index.ts
Stablecoin from Inverse Finance
https://www.inverse.finance
Twitter:
https://twitter.com/InverseFinance
Symbol:
DOLA
Coingecko api id:
dola-usd
DOLA logo:
https://assets.coingecko.com/coins/images/14287/small/anchor-logo-1-200x200.png?1615275005
=> add DOLA adapter

src/adapters/peggedAssets/ratio-stable-coin/index.ts, src/adapters/peggedAssets/ratio-stable-coin/ratio-state.json
Stable Coin from Ratio Finance
https://ratio.finance/
Twitter:
https://twitter.com/ratiofinance
Symbol:
USDr
Coingecko api id:
ratio-stable-coin
USDr logo:
=> Add ratio USDr

src/peggedData/peggedData.ts
=> Update USDX wiki link

src/adapters/peggedAssets/digitaldollar/index.ts, src/adapters/peggedAssets/index.ts
Please review this request to add DUSD. 
DigitalDollar (DUSD): The stable coin by Fluid Finance.
Website: https://fluid.ch
CoinGecko: https://www.coingecko.com/en/coins/digitaldollar
Thanks.
=> Add DigitalDollar DUSD.

src/adapters/peggedAssets/helio-protocol-hay/index.ts
- Added Helio Protocol Hay destable coin
=> helio-protocol-hay destable coin added

src/adapters/peggedAssets/bank-of-chain/index.ts
https://defillama.com/yields/pool/78981869-d2c1-4fe1-94e5-68ba2cf95ae1
=> bank-of-chain's peggedUSD.

src/adapters/peggedAssets/bank-of-chain/index.ts
Reverts DefiLlama/peggedassets-server#25
=> Revert "Revert "bank-of-chain's peggedUSD.""

src/adapters/peggedAssets/dola-usd/index.ts
=> add dola bsc chain

src/adapters/peggedAssets/dola-usd/index.ts
=> add correct address Dola USD

src/adapters/peggedAssets/meme-dollar/index.ts
=> Add Meme-Dollar(PINA)

src/adapters/peggedAssets/index.ts, src/peggedData/peggedData.ts
=> Add Meme coin (PINA)

src/peggedData/peggedData.ts
=> remove space from name euroe

src/adapters/peggedAssets/dola-usd/index.ts
=> Add arbitrum network DOLA

src/adapters/peggedAssets/dai/index.ts, src/adapters/peggedAssets/helper/mixin.ts, src/adapters/peggedAssets/tether/index.ts, src/adapters/peggedAssets/usd-coin/index.ts
Replicate Mixin PR without package.json changes
=> Replicate Mixin PR without package.json changes

src/adapters/peggedAssets/dola-usd/index.ts
=> add avax chain to dola

src/utils/normalizeChain.ts
rename chain zksync to zksync lite
=> rename chain zksync to zksync lite

src/adapters/peggedAssets/eusd/index.ts, src/adapters/peggedAssets/index.ts
=> Add pegged asset eUSD

src/peggedData/peggedData.ts
add correct token address to MIM
=> add correct token address to MIM

src/adapters/peggedAssets/bob/index.ts
=> add arbitrum support BOB

src/adapters/peggedAssets/liquity-usd/index.ts, src/adapters/peggedAssets/usd-coin/index.ts
=> added zkSync Era

src/utils/normalizeChain.ts
Potencial Fix zkera chain missing values. (Test)
=> Potencial Fix zkera chain missing values. (Test)

src/adapters/peggedAssets/euroe-stablecoin/index.ts
EUROe has been deployed on Avalanche natively.
Cross reference addresses at https://dev.euroe.com/docs/Stablecoin/contract-addresses#avalanche-addresses
=> Add Avalanche adapter

src/adapters/peggedAssets/euroe-stablecoin/index.ts
=> fix avalanche name

src/adapters/peggedAssets/index.ts, src/adapters/peggedAssets/r/index.ts, src/peggedData/peggedData.ts
=> add R stablecoin

src/peggedData/peggedData.ts
fix real USD (remove old coingecko id)
=> fix real USD (remove old coingecko id)

src/peggedData/peggedData.ts
=> remove old cg ids

src/adapters/peggedAssets/binance-usd/index.ts
=> update thundercore busd

src/adapters/peggedAssets/davos-protocol/index.ts, src/peggedData/peggedData.ts
add support for ETH network on Davos Protocol
=> add support for ETH network on Davos Protocol

src/adapters/peggedAssets/tether/index.ts
=> Usdt to kava

src/adapters/peggedAssets/dei-token/index.ts
=> set total supply to 0 DEI

src/adapters/peggedAssets/dei-token/index.ts
=> set dei-token to 1

src/adapters/peggedAssets/grai/index.ts
add grai bridge instead of minting (for now)
=> add grai bridge instead of minting (for now)

src/adapters/peggedAssets/dai/index.ts
fix DAI (remove 3 bridged multichain)
=> fix DAI (remove 3 bridged multichain)

src/adapters/peggedAssets/liquity-usd/index.ts
temp fix lusd (remove era and polygon zk)
=> temp fix lusd (remove era and polygon zk)

src/adapters/peggedAssets/dai/index.ts
remove ethclassic multichain from dai
=> remove ethclassic multichain from dai

src/peggedData/peggedData.ts
=> add new token address to DEI

src/adapters/peggedAssets/gho/index.ts, src/adapters/peggedAssets/index.ts, src/peggedData/peggedData.ts
There's an Aave proposal active to launch GHO (https://app.aave.com/governance/proposal/?proposalId=268). This PR adds in an adapter to support it.
Note the tests will currently fail until the proposal is executed,  just getting this PR up so it's ready to go.
=> Gho adapter

src/adapters/peggedAssets/first-digital-usd/index.ts, src/adapters/peggedAssets/index.ts
=> WIP first digital usd 

src/peggedData/peggedData.ts
Please cross-reference the information at https://www.euroe.com/due-diligence-resources
=> Fix EUROe description

src/adapters/peggedAssets/index.ts, src/adapters/peggedAssets/star/index.ts, src/peggedData/peggedData.ts
Added star stable coin(debt token) for [preon finance](https://preon.finance)
=> Add star stable coin for preon

src/adapters/peggedAssets/index.ts, src/peggedData/peggedData.ts
=> listing Alternity CNY

src/adapters/peggedAssets/index.ts, src/adapters/peggedAssets/nexus/index.ts
add Nexus stable coin project on Etherum Mainnet and Arbitrum One
=> add nexus (NEX) adapter

package-lock.json, src/adapters/package-lock.json, src/adapters/peggedAssets/usd-coin/index.ts
=> add native USDC to near WIP

src/adapters/peggedAssets/index.ts, src/adapters/peggedAssets/phase-dollar/config.ts, src/adapters/peggedAssets/phase-dollar/index.ts
Added CASH (Phase Dollar) to the pegged assets.
https://www.coingecko.com/en/coins/phase-dollar
=> Added phase-dollar

src/adapters/peggedAssets/euroe-stablecoin/index.ts
Cross reference contract addresses in original documentation here: https://dev.euroe.com/docs/Stablecoin/contract-addresses#optimism
=> add EUROe on Optimism

src/adapters/peggedAssets/high-yield-usd/index.ts, src/adapters/peggedAssets/index.ts
Adding High Yield USD eth and base
=> Adding High Yield USD

src/adapters/peggedAssets/peggedAsset.type.ts, src/peggedData/types.ts
add support for CAD (canadian dollar)
=> add support for CAD (canadian dollar)

src/adapters/peggedAssets/davos-protocol/index.ts
=> add missing chains to davos

src/adapters/peggedAssets/anchored-coins-eur/index.ts, src/adapters/peggedAssets/index.ts, src/peggedData/peggedData.ts
Add EUR stablecoin Anchored Coins (AEUR)
Site: https://anchoredcoins.com
=> Add Anchored Coins AEUR

src/adapters/peggedAssets/usd-coin/index.ts
Stablecoin Mcap for base would increase by 180M$ adding base USDC native
=> add usdc (natively issued) for base to stablecoin tvl

src/adapters/peggedAssets/usdm/index.ts
Add other chains for USDM to the stablecoin section.
=> Adding new chains to stablecoin

src/adapters/peggedAssets/index.ts, src/adapters/peggedAssets/sable-coin/index.ts
Adding USDS Stablecoin bsc and base
=> Adding USDS Stablecoin bsc and base

src/adapters/peggedAssets/sovryn-dollar/index.ts
This PR aims to add Sovryn Dollar to Defillama. For more information about it:
- https://wiki.sovryn.com/en/sovryn-dapp/sovryn-dollar
- https://sovryn.com/sovryn-dollar
- CMC:  https://coinmarketcap.com/currencies/sovryn-dollar/
- https://www.coingecko.com/en/coins/sovryn-dollar
- https://rootstock.blockscout.com/token/0xc1411567D2670E24D9c4Daaa7CdA95686E1250Aa
Ticker: DLLR
Icon: https://github.com/rsksmart/rsk-contract-metadata/blob/master/images/dllr.png
=> Add Sovryn Dollar

src/adapters/package-lock.json, src/adapters/peggedAssets/helper/chains.json, src/adapters/peggedAssets/magic-internet-money/index.ts, src/peggedData/bridgeData.ts
Also fixes an issue where Linea is shown as not-found.
=> feat(abracadabra): Add support for Blast

src/adapters/peggedAssets/novatti-australian-digital-dollar/index.ts
AUDD is an Australian Dollar Stablecoin available on Ethereum, Stellar, XRP Ledger, and Solana. For any further queries please email blockchain@novatti.com or visit https://audd.digital
=> Addition of AUDD to Stablecoin Adapters

src/adapters/peggedAssets/cygnus-finance-global-usd/index.ts
GM! Here is the basic information of Cygnus Global USD:
1. Token Name: Cygnus Global USD
2. Ticker: cgUSD
3. Icon: https://www.cygnus.finance/tokens/cgUSD.png
4. website: https://www.cygnus.finance
5. Chain: Base
6. Address: 0xCa72827a3D211CfD8F6b00Ac98824872b72CAb49
=> Add Cygnus Global USD(pegged with USD)

src/adapters/peggedAssets/feth/index.ts, src/adapters/peggedAssets/fxusd/index.ts, src/adapters/peggedAssets/index.ts, src/peggedData/peggedData.ts
=> add Fractional ETH and fxUSD

src/utils/normalizeChain.ts
Reverts DefiLlama/peggedassets-server#281
=> Revert "change Optimism chain to OP Mainnet"

src/adapters/peggedAssets/index.ts, src/adapters/peggedAssets/web-3-dollar/index.ts, src/peggedData/peggedData.ts
We would like to integrate the web 3 dollar, an RToken that just launched on the reserve protocol.
=> web 3 dollar

src/adapters/peggedAssets/index.ts, src/adapters/peggedAssets/zun-eth/index.ts, src/adapters/peggedAssets/zun-usd/index.ts, src/peggedData/peggedData.ts
Following the discussion in #296 added new zunUSD and zunETH pegged asset
=> add zunUSD and zunETH pegged assets

src/adapters/peggedAssets/index.ts, src/adapters/peggedAssets/magma-wen/index.ts, src/peggedData/peggedData.ts
=> Adapter + listing Magma Wen

src/adapters/peggedAssets/index.ts, src/adapters/peggedAssets/international-stable-currency/index.ts
**name** : International Stable Currency
**address** : J9BcrQfX4p9D1bvLzRNCbMDv8f44a9LFdeqNE4Yk2WMD
**symbol** : ISC
**url** : https://isc.money
**description** : International Stable Currency (ISC) is yield-bearing stablecoin pegged to a basket of real world assets.
**mintRedeemDescription** : ISC Issuer is tasked with two principal functions that are integral to the operation of the ISC ecosystem. Firstly, it is responsible for the minting and burning of ISC. Secondly, it manages the loans of ISC between itself and the ISC Reserves.
**gecko_id** : international-stable-currency
**twitter** : https://twitter.com/ISC_money
**wiki** : https://wp.isc.money
**logo_url**  : https://github.com/theISCTeam/isc_meta/blob/master/logo.png
**logo** :
=> Adapter + Listing ISC

src/adapters/peggedAssets/index.ts, src/adapters/peggedAssets/knox-dollar/index.ts, src/peggedData/peggedData.ts
Hi, I would like to add KNOX Dollar to defillama
=> KNOX Dollar 

src/adapters/peggedAssets/btcUSD/index.ts
Add the btcUSD Stable coin to Defillama.
Website: https://fx.aladdin.club/
=> Add btcUSD

src/adapters/peggedAssets/bitusd/index.ts, src/adapters/peggedAssets/helper/chains.json, src/utils/normalizeChain.ts
Add bitlayer support + bitusd adapter
=> Add bitlayer support + bitusd adapter

src/adapters/peggedAssets/ondo-us-dollar-yield/index.ts
USDYc represents USDY that was already purchased, but is within the 40 day holding period. This PR is to add the USDYc supply into the USDY tvl.
=> Add usdyc to usdy

src/adapters/peggedAssets/index.ts, src/adapters/peggedAssets/resolv-usr/index.ts, src/peggedData/peggedData.ts
Website: https://www.resolv.im/
App: https://beta.resolv.im/overview
Docs: https://docs.resolv.im/
```bash
npx ts-node --transpile-only test.ts resolv-usr peggedUSD   
--- ethereum ---
minted                    9.20 M
circulating               9.20 M
Total circulating         9.20 M
```
@g1nt0ki @Define101 🙏
=> add USR pegged asset

src/adapters/peggedAssets/euro-coin/index.ts
Circle has been issuing EUROC on Stellar since September. This commit adds the Stellar network to the existing pegged asset page on DefiLlama.
I copied the `circleAPIChainMinted()` function from the [Circle `usd-coin/index.ts` file](https://github.com/DefiLlama/peggedassets-server/blob/7551d885fd42197ba89d060636649578b3c252f8/src/adapters/peggedAssets/usd-coin/index.ts#L195).
=> adds Stellar to the networks with EUROC by Circle

src/adapters/peggedAssets/helper/stellar.ts, src/adapters/peggedAssets/stasis-eurs/index.ts
This commit adds EURS by Stasis, issued on Stellar as a pegged asset.
I'm also planning a few more PRs, relating to other stablecoins we have issued on the network. So, I made a file with some helper functions to facilitate those. It was a little tricky to figure out precisely the "best" or "preferred" way of defining and using those kinds of helper functions. If there are some changes you'd like me to make to the way I did it, I'm happy to do so.
Thanks!
=> add Stasis EURS on Stellar

src/adapters/peggedAssets/hedera-swiss-franc/index.ts, src/adapters/peggedAssets/index.ts
We want to submit HCHF on Hedera—a Swiss franc stablecoin on the Hedera network.
=> - Add HCHF (Coingeko id: hedera-swiss-franc)

src/adapters/peggedAssets/vnx-euro/index.ts, src/adapters/peggedAssets/vnx-swiss-franc/index.ts
[VNX](https://vnx.li) has a couple assets issued on the Stellar network: `VEUR` and `VCHF`. This PR adds information for the Stellar version of those assets.
=> Add relevant VNX assets on the Stellar network

src/adapters/peggedAssets/dackie-usd/index.ts
Docs: https://docs.dackieswap.xyz/products/product-features/dackie-usd-dckusd
Blogs: https://dackie.mirror.xyz/8dJ-Q-FtZngv7dgq2b_gr5xhwxwA3rJoxHBbepM5ggw
Tweet: https://x.com/DackieSwap/status/1827777488875057437
https://www.coingecko.com/en/coins/dackie-usd
=> Listing Dackie USD (dckUSD) in stable coin assets

src/adapters/peggedAssets/binance-peg-busd/index.ts, src/adapters/peggedAssets/binance-usd/index.ts, src/adapters/peggedAssets/dai/config.ts, src/adapters/peggedAssets/frax-price-index/index.ts, src/adapters/peggedAssets/frax/index.ts, src/adapters/peggedAssets/liquity-usd/index.ts, src/adapters/peggedAssets/tether/config.ts, src/adapters/peggedAssets/tether/index.ts, src/adapters/peggedAssets/usd-coin/config.ts, src/adapters/peggedAssets/usd-coin/index.ts
- Add Native Minted USDC
- Add Frax FPI
- Add Celer Bridged BUSD
- Add FRAX
- Fix USDT
- Update ZKsync Era bridge address on Ethereum
=> Improve Stables on ZKsync Era

src/adapters/peggedAssets/ondo-us-dollar-yield/index.ts
The Mantle balance for USDY references an `unreleased` address pointing to an unknown multisig. This should be removed, as we consider all tokens on Mantle to be in circulation.
The Noble and Injective balance funcitons have been reworked to use the native Noble RPC and fetch balances using the IBC channel balances. This is a lot more scalable, and I was able to add Osmosis as well.
=> Ondo USDY: fix mantle and cosmos chain balances

src/peggedData/peggedData.ts
Fix metadata for [uaht.io](https://uaht.io/) project.
=> Update UAHT peggedData.ts

src/adapters/peggedAssets/bean2/index.ts, src/adapters/peggedAssets/index.ts
Reverts DefiLlama/peggedassets-server#401
=> Revert "Bean token on Arbitrum"

src/adapters/peggedAssets/helper/chains.json, src/adapters/peggedAssets/index.ts, src/adapters/peggedAssets/usda/index.ts
Add asset:  Avalon USDa
https://www.coingecko.com/en/coins/usda
=> Add asset:  Avalon USDa

src/adapters/peggedAssets/magic-internet-money/index.ts
Cauldrons added to the MIM adapter:
- **Arbitrum**
- [ZRO](https://arbiscan.io/address/0x6B04C535C852AD19345571247ee12B5BF23dAcB6)
- [ENA](https://arbiscan.io/address/0xFCE0b2fe7d7d5057C82A896e4D8EC0e4b813f71f)
- **Mainnet**
- [sdeUSD V2](https://etherscan.io/address/0x38E7D1e4E2dE5b06b6fc9A91C2c37828854A41bb)
- [USD0++](https://etherscan.io/address/0xE8ed7455fa1b2a3D8959cD2D59c7f136a45BF341)
=> feat(abracadabra): Add various new cauldrons

src/adapters/peggedAssets/index.ts, src/adapters/peggedAssets/pausd-stablecoin/index.ts
Add paUSD stablecoin (usd pegged asset)
What is paUSD: https://docs.mimo.capital/parallel-protocol/parallel-protocol/par-1 
coingecko price: https://www.coingecko.com/en/coins/parallel-usd
=> feat: implement paUSD stablecoin (Parallel Protocol)

src/adapters/peggedAssets/helper/getSupply.ts, src/adapters/peggedAssets/monerium-eur-money/index.ts, src/adapters/peggedAssets/ondo-us-dollar-yield/index.ts
=> Fix: adapter dependent on Noble chain

src/adapters/peggedAssets/usdm/index.ts
Added the Zk Sync address for USDM.
=> Adding zkSync

src/adapters/peggedAssets/helper/chains.json, src/adapters/peggedAssets/usd-coin/config.ts, src/adapters/peggedAssets/usd-coin/index.ts, src/utils/normalizeChain.ts
=> Adding Soneium chain + USDC

src/adapters/peggedAssets/index.ts, src/adapters/peggedAssets/noon-usn/index.ts, src/peggedData/peggedData.ts
Adding USN pegged USD
Infos : 
- https://noon.capital
- https://twitter.com/noon_capital
- https://docs.noon.capital
=> Add NOON USN

src/utils/normalizeChain.ts
updating chain details and name, in an attempt to get world chain values to populate on this page - https://defillama.com/stablecoins/Wc
=> Update normalizeChain.ts to fix world chain

src/adapters/peggedAssets/cadc/index.ts
Add CADC on Base to CADC stablecoin
=> chore: add cadc on base

src/adapters/peggedAssets/index.ts, src/adapters/peggedAssets/stablr-euro/index.ts, src/adapters/peggedAssets/stablr-usd/index.ts
Tokens added:
**StablR Euro (EURR)**
_Ethereum Contracts:_ 
`0x50753CfAf86c094925Bf976f218D043f8791e408` `0xdaC306D72f48dbaD805a11CBf7A512A277C084C9`
_Solana Contracts:_ 
`HViRSvsTpwubWHevjSPxNB22Fg3kdzXtedfQXmMoHtoZ`
**StablR USD (USDR)**
_Ethereum Contracts:_ 
`0x7B43E3875440B44613DC3bC08E7763e6Da63C8f8`
All contract addresses are displayed on [stablr.com](stablr.com)
=> Add 'StablR EUR'(EURR) and 'StablR USD'(USDR) Stablecoins

src/adapters/peggedAssets/helper/chains.json, src/adapters/peggedAssets/noon-usn/index.ts, src/utils/normalizeChain.ts
=> peggedAsset update - noon usn

src/adapters/peggedAssets/index.ts, src/adapters/peggedAssets/usda/index.ts
- Includes Anzens Cardano USDA stablecoin
- Website: https://anzens.com
- X: https://x.com/AnzensOfficial
=> chore: add cardano USDA

src/adapters/peggedAssets/index.ts, src/adapters/peggedAssets/schuman-europ/index.ts
EURØP is a secure, transparent, and MiCA-compliant euro-denominated stablecoin, redeemable 1:1 for the euro. It is issued by a licensed stablecoin issuer and regulated by the French banking authority ACPR. Each EURØP is 100% backed by euros, with reserves held in government-supervised EU banks such as Société Générale. Our reserves are audited by KPMG, one of the world’s leading audit firms.
Website: https://schuman.io/
White Paper: https://schuman.io/wp-content/uploads/2025/02/EUROP-White-Paper_1.3.pdf
=> schuman-europ

src/adapters/peggedAssets/glo-dollar/index.ts
https://www.glodollar.org/articles/smart-contract-addresses
=> add vechain to glo-dollar

src/adapters/peggedAssets/brz/index.ts, src/adapters/peggedAssets/index.ts
The BRZ Token (Brazilian Digital Token) is present on several networks and needs to be added to DeFiLlama.
=> add brz token

src/adapters/peggedAssets/index.ts, src/adapters/peggedAssets/standx-dusd/index.ts
Hi team,
Requesting to add StandX DUSD ($DUSD) to the platform.
```
--- solana ---
minted                    15.02 M
circulating               15.02 M
--- bsc ---
minted                    5.06 M
circulating               5.06 M
Total circulating         20.07 M
```
Links:
- Website: [https://standx.com](https://standx.com)
- Icon: [https://github.com/standx-labs/stdc_assets/blob/main/images/dusd.png](https://github.com/standx-labs/stdc_assets/blob/main/images/dusd.png)
Thanks for your review!
=> Request to add StandX DUSD ($DUSD) to the platform

src/adapters/peggedAssets/usd-coin/config.ts, src/adapters/peggedAssets/usd-coin/index.ts
adding 
USDC.e on Corn - https://cornscan.io/token/0xDF0B24095e15044538866576754F3C964e902Ee6?chainid=21000000
USDC on X Layer - https://www.oklink.com/x-layer/token/0x74b7f16337b8972027f6196a17a631ac6de26d22
USDC on Flare - https://mainnet.flarescan.com/token/0xFbDa5F676cB37624f28265A144A48B0d6e87d3b6
USDC on Abstract - https://abscan.org/token/0x84a71ccd554cc1b02749b35d22f684cc8ec987e1
=> Adding Bridged USDC on Corn, Flare, Abstract, X Layer chains

src/adapters/peggedAssets/index.ts, src/adapters/peggedAssets/solomon-usdv/index.ts
Hi,
Requesting to add Solomon USDv.
It's just been listed under the basis trading category under the main website / repo (https://defillama.com/protocol/solomon-usdv).
```
--- solana ---
minted                    1.03 M
circulating               1.03 M
Total circulating         1.03 M
```
Links:
- Website: https://solomonlabs.org/
- Icon: https://solomonlabs.org/assets/USDv.svg
Thank you for your consideration.
=> Request to add Solomon USDv

src/adapters/peggedAssets/ethena-usde/index.ts, src/adapters/peggedAssets/helper/getSupply.ts
Adding Ethena [token contract on TON](https://docs.ethena.fi/solution-design/key-addresses)
=> Add Ethena on TON

src/adapters/peggedAssets/satoshi-stablecoin/index.ts, src/peggedData/peggedData.ts
Satoshi Protocol upgraded new V2 smart contracts,
Added new satUSD tokens
=> Update satUSD 

src/adapters/peggedAssets/ethena-usde/index.ts, src/adapters/peggedAssets/tether/config.ts, src/adapters/peggedAssets/tether/index.ts
=> adding hyperliquid stables

src/adapters/peggedAssets/usde/index.ts
website: https://xbanking.org/usde
ticker: USDE
icon: https://app.xbanking.org/assets/coins/usdelogo.png
=> add USDE stablecoin to stablecoins page on defillama

src/adapters/peggedAssets/index.ts, src/adapters/peggedAssets/mead-2/index.ts
Gm,
This is the peggedAssets adapter for MEAD by Roots
https://defillama.com/protocol/roots
https://www.coingecko.com/en/coins/mead-2
https://rootsfi.com/
=> adding MEAD by Roots

src/adapters/peggedAssets/helper/chains.json, src/adapters/peggedAssets/usbd/index.ts
- Added custom USBD supply calculation 
- Added Plume + Sonic + Goat + Binance smart chain networks
=> updated USBD Adapter

src/adapters/peggedAssets/usd-coin/config.ts, src/adapters/peggedAssets/usd-coin/index.ts
token: https://livenet.xrpl.org/token/5553444300000000000000000000000000000000.rGm7WCVp9gb4jZHWTEtGUr4dd74z2XuWhE
=> Add native xrpl usdc

src/adapters/peggedAssets/good-game-us-dollar/index.ts, src/adapters/peggedAssets/index.ts
=> Add GGUSD adapter

src/adapters/peggedAssets/index.ts, src/adapters/peggedAssets/xsgd/index.ts, src/peggedData/peggedData.ts
logo : https://github.com/DefiLlama/icons/pull/2222
=> feat: added xsgd

src/adapters/peggedAssets/autonomint-usda+/index.ts
Name: Autonomint
website: https://www.autonomint.com
docs: https://docs.autonomint.com/autonomint/
x Link: https://x.com/autonomint
=> added Autonomint usda+

src/adapters/peggedAssets/bilira/index.ts, src/adapters/peggedAssets/index.ts
=> Add Bilira Adapter

src/adapters/peggedAssets/satoshi-stablecoin/index.ts
River deployed new contractss on Ethereum, Sonic, X layer Chains
Added new satUSD tokens
=>  update River

src/adapters/peggedAssets/agora-dollar/index.ts
=> track ausd on katana

src/adapters/peggedAssets/ondo-us-dollar-yield/index.ts
**Name (to be shown on DefiLlama):** 
Ondo US Dollar Yield (Stellar)
**Website Link:**
https://ondo.finance
**Logo (High resolution, will be shown with rounded borders):**
Token already present
**Chain:**
Stellar
**Coingecko ID (leave empty if not listed):**
ondo-usdy
**Coinmarketcap ID (leave empty if not listed):**
25505
**Short Description:**
USDY is Ondo Finance's yield-bearing stablecoin that provides exposure to short-term US Treasuries and bank demand deposits. It's designed to offer institutional-grade yield while maintaining stability and liquidity for DeFi users.
**mintRedeemDescription:**
USDY can be minted by qualified investors through Ondo Finance's platform by depositing USD or USDC. The underlying assets generate yield through investments in short-term US Treasuries and …
=> Add Stellar USDY support to Ondo adapter

src/adapters/peggedAssets/avalon-usda/index.ts, src/adapters/peggedAssets/usd-coin/config.ts, src/adapters/peggedAssets/usd-coin/index.ts
1. [USDC (Startgate) on Nibiru](https://nibiscan.io/address/0x0829F361A05D993d5CEb035cA6DF3446b060970b/contract/6900/readProxyContract)
2. [adapters(avalon-usda): add Nibiru instance of USDa from Avalon](https://github.com/DefiLlama/peggedassets-server/pull/594/commits/2109f637d52f659a53497df4d7b6424827ccb143)
=> usd-coin: add nibiru USDC.e from LayerZero Stargate bridge; add Avalon USDa

src/peggedData/peggedData.ts
=> Update dTRINITY USD mint and redeem description

src/adapters/peggedAssets/helper/chains.json, src/adapters/peggedAssets/index.ts, src/adapters/peggedAssets/saga-dollar/index.ts
**NOTE**
---
Saga Dollar (D) is a fully backed stablecoin by an onchain reserve of other stablecoins and yield-bearing assets on SagaEVM. The yields generated by D’s reserve are redirected to its borrowers on integrated Saga lending protocols, such as [Palomino](https://palomino.fi/), to subsidize their interest expenses.
Users can mint and redeem Saga Dollar (D) with other stablecoins and yield-bearing assets on Colt protocol.
Address: https://sagaevm.sagaexplorer.io/token/0xB76144F87DF95816e8c55C240F874C554B4553C3
Ticker: D
Our OracleAggregator: https://sagaevm.sagaexplorer.io/address/0x889bf3E00e93Bc9CE17A7f8141ef109283913f37
=> Add saga dollar

src/adapters/peggedAssets/iAUSD/index.ts
**NOTE**
---
iAUSD is minted via iA Borrow, InshAllah's halal lending protocol. iAUSD is fully collateralized using iASOL collateral. iAUSD yield comes form profit sharing. The staking yield from iASOL is split between the iASOL collateral and minted iAUSD creating the first halal yield-bearing stablecoin
=> Add iAUSD stablecoin adapter
